config/routes.rb
Rails.application.routes.draw do
  resources :servicios
  resources :historial_pacientes
  resources :plan_quirurgicos
  resources :medicos
  resources :clinicas
  resources :especialidads
  resources :pacientes
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }
  root 'bienvenido#index'  
  resources :rols
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
      user ||= User.new # guest user (not logged in)
       if user.rol_id==2
       can :paciente, :all
       else
        can :read, :all
       end
    
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/clinica.rb
class Clinica < ApplicationRecord
  belongs_to :user, dependent: :destroy
  accepts_nested_attributes_for :user
  has_many :medicoen_clinicas
  has_many :medicos, through: :medicoen_clinicas
end

app/models/especialidad.rb
class Especialidad < ApplicationRecord
	self.table_name = "especialidads"
	has_many :medicos
end

app/models/historial_paciente.rb
class HistorialPaciente < ApplicationRecord
  belongs_to :paciente
end

app/models/medico.rb
class Medico < ApplicationRecord
  belongs_to :especialidad
  belongs_to :user, dependent: :destroy
  accepts_nested_attributes_for :user
  has_many :medicoen_clinicas
  has_many :clinicas, through: :medicoen_clinicas
  after_create :save_clinicas
  def clinicas=(value)
  	@clinicas = value
  end

  private
  def save_clinicas
  	@clinicas.each do |clinica_id|
  		MedicoenClinica.create(clinica_id: clinica_id, medico_id: self.id)
  	
  end
end
end

app/models/medicoen_clinica.rb
class MedicoenClinica < ApplicationRecord
  belongs_to :clinica
  belongs_to :medico
end

app/models/paciente.rb
class Paciente < ApplicationRecord
  belongs_to :user, dependent: :destroy
  accepts_nested_attributes_for :user
end

app/models/plan_quirurgico.rb
class PlanQuirurgico < ApplicationRecord
  belongs_to :medico
  belongs_to :paciente
  mount_uploader :examen, ExamenUploader
  has_many :servicio_seleccionados
  has_many :plan_quirurgicos, through: :servicio_seleccionados
  after_create :save_servicios
	  def servicios=(value)
	  	@servicios = value
	  end

	  private
	  	def save_servicios
	  		@servicios.each do |servicio_id|
	  			ServicioSeleccionado.create(servicio_id: servicio_id, plan_quirurgico_id: self.id)
	  	
	  	end
	  end
end

app/models/rol.rb
class Rol < ApplicationRecord
	self.table_name = "rols"
	has_many :users
end

app/models/servicio.rb
class Servicio < ApplicationRecord
  has_many :servicio_seleccionados
  has_many :plan_quirurgicos, through: :servicio_seleccionados
end

app/models/servicio_seleccionado.rb
class ServicioSeleccionado < ApplicationRecord
  belongs_to :servicio
  belongs_to :plan_quirurgico
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  belongs_to :rol
  has_one :paciente
  has_one :medico
  has_one :clinica

end

app/controllers/rols_controller.rb
class RolsController < ApplicationController
	before_action :set_rol, only: [:show, :edit, :update, :destroy]  
  # GET /rols
  # GET /rols.json
  def index
    @rols = Rol.where(:estatus => "A")
  end

  # GET /rols/1
  # GET /rols/1.json
  def show
  end

  # GET /rols/new
  def new
    @rol = Rol.new
  end

  # GET /rols/1/edit
  def edit
  end

  # POST /rols
  # POST /rols.json
  def create
    @rol = Rol.new(rol_params)
    @rol.estatus = "A" 
    respond_to do |format|
      if @rol.save
        format.html { redirect_to @rol, notice: 'El Rol ha sido creado exitosamente.' }
        format.json { render :show, status: :created, location: @rol }
      else
        format.html { render :new }
        format.json { render json: @rol.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rols/1
  # PATCH/PUT /rols/1.json
  def update
    respond_to do |format|
      if @rol.update(rol_params)
        format.html { redirect_to @rol, notice: 'El Rol ha sido modificado exitosamente.' }
        format.json { render :show, status: :ok, location: @rol }
      else
        format.html { render :edit }
        format.json { render json: @rol.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rols/1
  # DELETE /rols/1.json
  def destroy
    @rol = Rol.find(params[:id])
    @rol.estatus = 'I'      
    @rol.save
    respond_to do |format|
      format.html { redirect_to rols_url, notice: 'El rol ha sido eliminado exitosamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rol
      @rol = Rol.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rol_params
      params.require(:rol).permit(:descripcion, :estatus)
    end
end

app/controllers/servicios_controller.rb
class ServiciosController < ApplicationController
  before_action :set_servicio, only: [:show, :edit, :update, :destroy]

  # GET /servicios
  # GET /servicios.json
  def index
    @servicios = Servicio.where(:estatus => "A")
  end

  # GET /servicios/1
  # GET /servicios/1.json
  def show
  end

  # GET /servicios/new
  def new
    @servicio = Servicio.new
  end

  # GET /servicios/1/edit
  def edit
  end

  # POST /servicios
  # POST /servicios.json
  def create
    @servicio = Servicio.new(servicio_params)
    @servicio.estatus = "A"
    respond_to do |format|
      if @servicio.save
        format.html { redirect_to @servicio, notice: 'Servicio was successfully created.' }
        format.json { render :show, status: :created, location: @servicio }
      else
        format.html { render :new }
        format.json { render json: @servicio.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /servicios/1
  # PATCH/PUT /servicios/1.json
  def update
    respond_to do |format|
      if @servicio.update(servicio_params)
        format.html { redirect_to @servicio, notice: 'Servicio was successfully updated.' }
        format.json { render :show, status: :ok, location: @servicio }
      else
        format.html { render :edit }
        format.json { render json: @servicio.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /servicios/1
  # DELETE /servicios/1.json
  def destroy
    @servicios = Servicio.find(params[:id])
    @servicio.estatus = "I"
    @servicio.save 
    respond_to do |format|
      format.html { redirect_to servicios_url, notice: 'Servicio was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_servicio
      @servicio = Servicio.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def servicio_params
      params.require(:servicio).permit(:costo, :descripcion, :estatus)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bienvenido_helper.rb
module BienvenidoHelper
end

app/helpers/clinicas_helper.rb
module ClinicasHelper
end

app/helpers/especialidads_helper.rb
module EspecialidadsHelper
end

app/helpers/medicos_helper.rb
module MedicosHelper
end

app/helpers/pacientes_helper.rb
module PacientesHelper
end

app/helpers/rols_helper.rb
module RolsHelper
end

app/helpers/servicios_helper.rb
module ServiciosHelper
end

app/views/servicios/_form.html.erb
<%= form_with(model: servicio, local: true) do |form| %>
  <% if servicio.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(servicio.errors.count, "error") %> prohibited this servicio from being saved:</h2>

      <ul>
      <% servicio.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :costo %>
    <%= form.text_field :costo, id: :servicio_costo %>
  </div>

  <div class="field">
    <%= form.label :descripcion %>
    <%= form.text_field :descripcion, id: :servicio_descripcion %>
  </div>

  <div class="field">
    <%= form.label :estatus %>
    <%= form.text_field :estatus, id: :servicio_estatus %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/servicios/edit.html.erb
<h1>Editing Servicio</h1>

<%= render 'form', servicio: @servicio %>

<%= link_to 'Show', @servicio %> |
<%= link_to 'Back', servicios_path %>

app/views/servicios/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Servicios</h1>

<table>
  <thead>
    <tr>
      <th>Costo</th>
      <th>Descripcion</th>
      <th>Estatus</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @servicios.each do |servicio| %>
      <tr>
        <td><%= servicio.costo %></td>
        <td><%= servicio.descripcion %></td>
        <td><%= servicio.estatus %></td>
        <td><%= link_to 'Show', servicio %></td>
        <td><%= link_to 'Edit', edit_servicio_path(servicio) %></td>
        <td><%= link_to 'Destroy', servicio, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Servicio', new_servicio_path %>

app/views/servicios/new.html.erb
<h1>New Servicio</h1>

<%= render 'form', servicio: @servicio %>

<%= link_to 'Back', servicios_path %>

app/views/servicios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Costo:</strong>
  <%= @servicio.costo %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @servicio.descripcion %>
</p>

<p>
  <strong>Estatus:</strong>
  <%= @servicio.estatus %>
</p>

<%= link_to 'Edit', edit_servicio_path(@servicio) %> |
<%= link_to 'Back', servicios_path %>