config/routes.rb
Rails.application.routes.draw do
  resources :servicios
  resources :historial_pacientes
  resources :plan_quirurgicos
  resources :medicos
  resources :clinicas
  resources :especialidads
  resources :pacientes
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }
  root 'bienvenido#index'  
  resources :rols
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
      user ||= User.new # guest user (not logged in)
       if user.rol_id==2
       can :paciente, :all
       else
        can :read, :all
       end
    
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/clinica.rb
class Clinica < ApplicationRecord
  belongs_to :user, dependent: :destroy
  accepts_nested_attributes_for :user
  has_many :medicoen_clinicas
  has_many :medicos, through: :medicoen_clinicas
end

app/models/especialidad.rb
class Especialidad < ApplicationRecord
	self.table_name = "especialidads"
	has_many :medicos
end

app/models/historial_paciente.rb
class HistorialPaciente < ApplicationRecord
  belongs_to :paciente
end

app/models/medico.rb
class Medico < ApplicationRecord
  belongs_to :especialidad
  belongs_to :user, dependent: :destroy
  accepts_nested_attributes_for :user
  has_many :medicoen_clinicas
  has_many :clinicas, through: :medicoen_clinicas
  after_create :save_clinicas
  def clinicas=(value)
  	@clinicas = value
  end

  private
  def save_clinicas
  	@clinicas.each do |clinica_id|
  		MedicoenClinica.create(clinica_id: clinica_id, medico_id: self.id)
  	
  end
end
end

app/models/medicoen_clinica.rb
class MedicoenClinica < ApplicationRecord
  belongs_to :clinica
  belongs_to :medico
end

app/models/paciente.rb
class Paciente < ApplicationRecord
  belongs_to :user, dependent: :destroy
  accepts_nested_attributes_for :user
end

app/models/plan_quirurgico.rb
class PlanQuirurgico < ApplicationRecord
  belongs_to :medico
  belongs_to :paciente
  mount_uploader :examen, ExamenUploader
  has_many :servicio_seleccionados
  has_many :plan_quirurgicos, through: :servicio_seleccionados
  after_create :save_servicios
	  def servicios=(value)
	  	@servicios = value
	  end

	  private
	  	def save_servicios
	  		@servicios.each do |servicio_id|
	  			ServicioSeleccionado.create(servicio_id: servicio_id, plan_quirurgico_id: self.id)
	  	
	  	end
	  end
end

app/models/rol.rb
class Rol < ApplicationRecord
	self.table_name = "rols"
	has_many :users
end

app/models/servicio.rb
class Servicio < ApplicationRecord
  has_many :servicio_seleccionados
  has_many :plan_quirurgicos, through: :servicio_seleccionados
end

app/models/servicio_seleccionado.rb
class ServicioSeleccionado < ApplicationRecord
  belongs_to :servicio
  belongs_to :plan_quirurgico
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  belongs_to :rol
  has_one :paciente
  has_one :medico
  has_one :clinica

end

app/controllers/pacientes_controller.rb
class PacientesController < ApplicationController
  before_action :set_paciente, only: [:show, :edit, :update, :destroy]

  # GET /pacientes
  # GET /pacientes.json
  def index
    @pacientes = Paciente.where(:estatus => "A")

  end

  # GET /pacientes/1
  # GET /pacientes/1.json
  def show
  end

  # GET /pacientes/new
  def new
    @paciente = Paciente.new
    @paciente.user = User.new
  end

  # GET /pacientes/1/edit
  def edit
  end

  # POST /pacientes
  # POST /pacientes.json
  def create
    @paciente = Paciente.new(paciente_params)
    @paciente.estatus = "A" 
    respond_to do |format|
      if @paciente.save
        format.html { redirect_to @paciente, notice: 'El paciente fue registrado exitosamente.' }
        format.json { render :show, status: :created, location: @paciente }
      else
        format.html { render :new }
        format.json { render json: @paciente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pacientes/1
  # PATCH/PUT /pacientes/1.json
  def update
    respond_to do |format|
      if @paciente.update(paciente_params)
        format.html { redirect_to @paciente, notice: 'Los datos del paciente han sido modificado con éxito' }
        format.json { render :show, status: :ok, location: @paciente }
      else
        format.html { render :edit }
        format.json { render json: @paciente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pacientes/1
  # DELETE /pacientes/1.json
  def destroy
    @paciente = Paciente.find(params[:id])
    @paciente.estatus = 'I'      
    @paciente.save
    respond_to do |format|
      format.html { redirect_to pacientes_url, notice: 'El paciente ha sido eliminado con éxito' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_paciente
      @paciente = Paciente.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def paciente_params
      params.require(:paciente).permit(:user_id, :ced_paciente, :nombres, :apellidos, :nombres_responsable, :apellidos_responsable, :telefono_responsable, :direccion, :telefono, :edad, :sexo, :estatus, user_attributes: [:email, :password, :password_confirmation, :rol_id])
    end
end

app/controllers/rols_controller.rb
class RolsController < ApplicationController
	before_action :set_rol, only: [:show, :edit, :update, :destroy]  
  # GET /rols
  # GET /rols.json
  def index
    @rols = Rol.where(:estatus => "A")
  end

  # GET /rols/1
  # GET /rols/1.json
  def show
  end

  # GET /rols/new
  def new
    @rol = Rol.new
  end

  # GET /rols/1/edit
  def edit
  end

  # POST /rols
  # POST /rols.json
  def create
    @rol = Rol.new(rol_params)
    @rol.estatus = "A" 
    respond_to do |format|
      if @rol.save
        format.html { redirect_to @rol, notice: 'El Rol ha sido creado exitosamente.' }
        format.json { render :show, status: :created, location: @rol }
      else
        format.html { render :new }
        format.json { render json: @rol.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rols/1
  # PATCH/PUT /rols/1.json
  def update
    respond_to do |format|
      if @rol.update(rol_params)
        format.html { redirect_to @rol, notice: 'El Rol ha sido modificado exitosamente.' }
        format.json { render :show, status: :ok, location: @rol }
      else
        format.html { render :edit }
        format.json { render json: @rol.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rols/1
  # DELETE /rols/1.json
  def destroy
    @rol = Rol.find(params[:id])
    @rol.estatus = 'I'      
    @rol.save
    respond_to do |format|
      format.html { redirect_to rols_url, notice: 'El rol ha sido eliminado exitosamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rol
      @rol = Rol.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rol_params
      params.require(:rol).permit(:descripcion, :estatus)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bienvenido_helper.rb
module BienvenidoHelper
end

app/helpers/clinicas_helper.rb
module ClinicasHelper
end

app/helpers/especialidads_helper.rb
module EspecialidadsHelper
end

app/helpers/medicos_helper.rb
module MedicosHelper
end

app/helpers/pacientes_helper.rb
module PacientesHelper
end

app/helpers/rols_helper.rb
module RolsHelper
end

app/helpers/servicios_helper.rb
module ServiciosHelper
end

app/views/pacientes/_form.html.erb
<div class="row center-xs">
  <div class="col-xs-8 col-md-6">
  <div class="box">

<%= form_with(model: paciente, local: true) do |form| %>
  <% if paciente.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(paciente.errors.count, "error") %> prohibited this paciente from being saved:</h2>

      <ul>
      <% paciente.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  
  <div class="field">
    <%= form.label :cedula %>
    <%= form.text_field :ced_paciente, id: :paciente_ced_paciente, class:"form-control"  %>
  </div>

  <div class="field">
    <%= form.label :nombres %>
    <%= form.text_field :nombres, id: :paciente_nombres, class:"form-control"  %>
  </div>

  <div class="field">
    <%= form.label :apellidos %>
    <%= form.text_field :apellidos, id: :paciente_apellidos, class:"form-control"  %>
  </div>

  <div class="field">
    <%= form.label :nombres_responsable %>
    <%= form.text_field :nombres_responsable, id: :paciente_nombres_responsable, class:"form-control"  %>
  </div>

  <div class="field">
    <%= form.label :apellidos_responsable %>
    <%= form.text_field :apellidos_responsable, id: :paciente_apellidos_responsable, class:"form-control"  %>
  </div>

  <div class="field">
    <%= form.label :telefono_responsable %>
    <%= form.text_field :telefono_responsable, id: :paciente_telefono_responsable , class:"form-control" %>
  </div>

  <div class="field">
    <%= form.label :direccion %>
    <%= form.text_field :direccion, id: :paciente_direccion, class:"form-control"  %>
  </div>

  <div class="field">
    <%= form.label :telefono %>
    <%= form.text_field :telefono, id: :paciente_telefono, class:"form-control"  %>
  </div>

  <div class="field">
    <%= form.label :edad %>
    <%= form.text_field :edad, id: :paciente_edad, class:"form-control"  %>
  </div>

  <div class="field">
    <%= form.label :sexo %>
    <%= form.text_field :sexo, id: :paciente_sexo, class:"form-control"  %>
  </div>

  <div class="actions ">
  <%= form.fields_for :user do |f| %>
    <% sexos = {'Masculino' => 0, 'Femenino' => 1} %>
      <fieldset>
        <div class="field">
            <%= f.label :email %><br />
            <%= f.email_field :email, autofocus: true, autocomplete: "email", class:"form-control" %>
          </div>

          <div class="field">
            <%= f.label :contraseña %>
            <% if @minimum_password_length %>
            <em>(<%= @minimum_password_length %> caracteres como mínimo)</em>
            <% end %><br />
            <%= f.password_field :password, autocomplete: "off", class:"form-control" %>

          </div>

          <div class="field">
            <%= f.label :confirmar_contraseña %><br />
            <%= f.password_field :password_confirmation, autocomplete: "off", class:"form-control" %>
          </div>
          
          <% #if not user_signed_in?%>
            <%= f.hidden_field :rol_id, :value => 2 %>
          <%#end%>

            <%= f.hidden_field :estatus, :value => "A" %>

          </fieldset> 
  <%end%>

    <%= form.submit "Guardar", class:"btn btn-primary b" %>
  </div>
<% end %>
</div>
</div>
</div>

app/views/pacientes/edit.html.erb
<div class="row center-xs">
  <div class="col-xs-8 col-md-6">
  <div class="box">
<h1>Editar Paciente</h1>

<%= render 'form', paciente: @paciente %>

<%#= link_to 'Ver', @paciente %> 
<%#= link_to 'Regresar', pacientes_path %>
</div>
</div>
</div>

app/views/pacientes/index.html.erb
<div class="row">
  <div class="col-xs-8 col-md-6">
  <div class="box">
<p id="notice"><%= notice %></p>

<h1 class="right">Lista de Pacientes</h1>

<table  width="203%" border="1" cellpadding="0" cellspacing="0" bordercolor="#2f4f4f">
  <thead>
    <tr>
      <th height="10%" width="10%">Nombres</th>
      <th height="10%" width="10%">Apellidos</th>
      <th height="10%" width="10%">Nombres responsable</th>
      <th height="10%" width="10%">Apellidos responsable</th>
      <th height="10%" width="10%">Telefono responsable</th>
      <th height="10%" width="10%">Direccion</th>
      <th height="10%" width="10%">Telefono</th>
      <th height="10%" width="10%">Edad</th>
      <th height="10%" width="10%">Sexo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pacientes.each do |paciente| %>
      <tr>
        <td height="10%" width="10%"><%= paciente.nombres %></td>
        <td height="10%" width="10%"><%= paciente.apellidos %></td>
        <td height="10%" width="10%"><%= paciente.nombres_responsable %></td>
        <td height="10%" width="10%"><%= paciente.apellidos_responsable %></td>
        <td height="10%" width="10%"><%= paciente.telefono_responsable %></td>
        <td height="10%" width="10%"><%= paciente.direccion %></td>
        <td height="10%" width="10%"><%= paciente.telefono %></td>
        <td height="10%" width="10%"><%= paciente.edad %></td>
        <td height="10%" width="10%"><%= paciente.sexo %></td>
        <td><%= link_to 'Ver', paciente %></td>
        <%# if can? :update, @article %>
        <td><%= link_to "Modificar", edit_paciente_path(paciente) %></td>
        <%# end %>        
        <td><%= link_to 'Eliminar', paciente, method: :delete, data: { confirm: '¿Esta seguro que desea eliminar al paciente?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'Registrar Nuevo Paciente', new_paciente_path %>
</div>
</div>
</div>

app/views/pacientes/new.html.erb
<div class="row center-xs">
  <div class="col-xs-8 col-md-6">
  <div class="box">
<h1>Nuevo Paciente</h1>

<%= render 'form', paciente: @paciente %>

<%#= link_to 'Regresar', pacientes_path %>
</div>
</div>
</div>

app/views/pacientes/show.html.erb
<div class="row center-xs">
  <div class="col-xs-8 col-md-6">
  <div class="box">
<p id="notice"><%= notice %></p>


<p>
  <strong>Ced paciente:</strong>
  <%= @paciente.ced_paciente %>
</p>

<p>
  <strong>Nombres:</strong>
  <%= @paciente.nombres %>
</p>

<p>
  <strong>Apellidos:</strong>
  <%= @paciente.apellidos %>
</p>

<p>
  <strong>Nombres responsable:</strong>
  <%= @paciente.nombres_responsable %>
</p>

<p>
  <strong>Apellidos responsable:</strong>
  <%= @paciente.apellidos_responsable %>
</p>

<p>
  <strong>Telefono responsable:</strong>
  <%= @paciente.telefono_responsable %>
</p>

<p>
  <strong>Direccion:</strong>
  <%= @paciente.direccion %>
</p>

<p>
  <strong>Telefono:</strong>
  <%= @paciente.telefono %>
</p>

<p>
  <strong>Edad:</strong>
  <%= @paciente.edad %>
</p>

<p>
  <strong>Sexo:</strong>
  <%= @paciente.sexo %>
</p>



<%= link_to 'Editar', edit_paciente_path(@paciente) %> |
<%= link_to 'Regresar', pacientes_path %>
</div>
</div>
</div>