config/routes.rb
Rails.application.routes.draw do
  resources :servicios
  resources :historial_pacientes
  resources :plan_quirurgicos
  resources :medicos
  resources :clinicas
  resources :especialidads
  resources :pacientes
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }
  root 'bienvenido#index'  
  resources :rols
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/historial_paciente.rb
class HistorialPaciente < ApplicationRecord
  belongs_to :paciente
end

app/controllers/historial_pacientes_controller.rb
class HistorialPacientesController < ApplicationController
  before_action :set_historial_paciente, only: [:show, :edit, :update, :destroy]

  # GET /historial_pacientes
  # GET /historial_pacientes.json
  def index
    @historial_pacientes = HistorialPaciente.where(:estatus => "A")
  end

  # GET /historial_pacientes/1
  # GET /historial_pacientes/1.json
  def show
  end

  # GET /historial_pacientes/new
  def new
    @historial_paciente = HistorialPaciente.new
  end

  # GET /historial_pacientes/1/edit
  def edit
  end

  # POST /historial_pacientes
  # POST /historial_pacientes.json
  def create
    @historial_paciente = HistorialPaciente.new(historial_paciente_params)
    @historial_paciente.estatus = "A"
    respond_to do |format|
      if @historial_paciente.save
        format.html { redirect_to @historial_paciente, notice: 'El Historial del paciente fue registrado exitosamente.' }
        format.json { render :show, status: :created, location: @historial_paciente }
      else
        format.html { render :new }
        format.json { render json: @historial_paciente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /historial_pacientes/1
  # PATCH/PUT /historial_pacientes/1.json
  def update
    respond_to do |format|
      if @historial_paciente.update(historial_paciente_params)
        format.html { redirect_to @historial_paciente, notice: 'Los datos del Historial del paciente han sido modificados exitosamente.' }
        format.json { render :show, status: :ok, location: @historial_paciente }
      else
        format.html { render :edit }
        format.json { render json: @historial_paciente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /historial_pacientes/1
  # DELETE /historial_pacientes/1.json
  def destroy
    @historial_paciente = HistorialPaciente.find(params[:id])
    @historial_paciente.estatus = 'I'      
    @historial_paciente.save
    respond_to do |format|
      format.html { redirect_to historial_pacientes_url, notice: 'El historial del paciente ha sido eliminado exitosamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_historial_paciente
      @historial_paciente = HistorialPaciente.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def historial_paciente_params
      params.require(:historial_paciente).permit(:paciente_id, :prob_cardio, :prob_respira, :diabetes, :alergias, :diab_pm, :sobrepso_pm, :hipertension_pm, :epilepsia_pm, :alcohol, :deportes, :tabaco, :drogas, :estatus)
    end
end

app/helpers/historial_pacientes_helper.rb
module HistorialPacientesHelper
end

app/views/historial_pacientes/_form.html.erb
<div class="row center-xs">
  <div class="col-xs-8 col-md-6">
  <div class="box">

<%= form_with(model: historial_paciente, local: true) do |form| %>
  <% if historial_paciente.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(historial_paciente.errors.count, "error") %> prohibited this historial_paciente from being saved:</h2>

      <ul>
      <% historial_paciente.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :paciente_id %>
    <%= form.text_field :paciente_id, id: :historial_paciente_paciente_id,  class:"form-control"  %>
  </div>

  <div class="field">
    <%= form.label :prob_cardio %>
    <%= form.check_box :prob_cardio, id: :historial_paciente_prob_cardio,  class:"form-control"  %>
  </div>

  <div class="field">
    <%= form.label :prob_respira %>
    <%= form.check_box :prob_respira, id: :historial_paciente_prob_respira,  class:"form-control"  %>
  </div>

  <div class="field">
    <%= form.label :diabetes %>
    <%= form.check_box :diabetes, id: :historial_paciente_diabetes,  class:"form-control" %>
  </div>

  <div class="field">
    <%= form.label :alergias %>
    <%= form.check_box :alergias, id: :historial_paciente_alergias,  class:"form-control"  %>
  </div>

  <div class="field">
    <%= form.label :diab_pm %>
    <%= form.text_field :diab_pm, id: :historial_paciente_diab_pm,  class:"form-control"  %>
  </div>

  <div class="field">
    <%= form.label :sobrepso_pm %>
    <%= form.text_field :sobrepso_pm, id: :historial_paciente_sobrepso_pm,  class:"form-control"  %>
  </div>

  <div class="field">
    <%= form.label :hipertension_pm %>
    <%= form.text_field :hipertension_pm, id: :historial_paciente_hipertension_pm,  class:"form-control"  %>
  </div>

  <div class="field">
    <%= form.label :epilepsia_pm %>
    <%= form.text_field :epilepsia_pm, id: :historial_paciente_epilepsia_pm,  class:"form-control"  %>
  </div>

  <div class="field">
    <%= form.label :alcohol %>
    <%= form.check_box :alcohol, id: :historial_paciente_alcohol,  class:"form-control"  %>
  </div>

  <div class="field">
    <%= form.label :deportes %>
    <%= form.check_box :deportes, id: :historial_paciente_deportes,  class:"form-control"  %>
  </div>

  <div class="field">
    <%= form.label :tabaco %>
    <%= form.check_box :tabaco, id: :historial_paciente_tabaco,  class:"form-control"  %>
  </div>

  <div class="field">
    <%= form.label :drogas %>
    <%= form.check_box :drogas, id: :historial_paciente_drogas,  class:"form-control"  %>
  </div>
  

  <div class="actions">
   <%= form.submit "Guardar", class:"btn btn-primary b" %>
  </div>
<% end %>
</div>
</div>
</div>

app/views/historial_pacientes/edit.html.erb
<div class="row center-xs">
  <div class="col-xs-8 col-md-6">
  <div class="box">

<h1>Editing Historial Paciente</h1>

<%= render 'form', historial_paciente: @historial_paciente %>

<%= link_to 'Ver', @historial_paciente %> |
<%= link_to 'Regresar', historial_pacientes_path %>
</div>
</div>
</div>

app/views/historial_pacientes/index.html.erb
<div class="row center-xs">
  <div class="col-xs-8 col-md-6">
  <div class="box">

<p id="notice"><%= notice %></p>

<h1>Listado Historial de Pacientes</h1>

<table>
  <thead>
    <tr>
      <th>Paciente</th>
      <th>Prob cardio</th>
      <th>Prob respira</th>
      <th>Diabetes</th>
      <th>Alergias</th>
      <th>Diab pm</th>
      <th>Sobrepso pm</th>
      <th>Hipertension pm</th>
      <th>Epilepsia pm</th>
      <th>Alcohol</th>
      <th>Deportes</th>
      <th>Tabaco</th>
      <th>Drogas</th>
      <th>Estatus</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @historial_pacientes.each do |historial_paciente| %>
      <tr>
        <td><%= historial_paciente.id %></td>
        <td><%= historial_paciente.prob_cardio %></td>
        <td><%= historial_paciente.prob_respira %></td>
        <td><%= historial_paciente.diabetes %></td>
        <td><%= historial_paciente.alergias %></td>
        <td><%= historial_paciente.diab_pm %></td>
        <td><%= historial_paciente.sobrepso_pm %></td>
        <td><%= historial_paciente.hipertension_pm %></td>
        <td><%= historial_paciente.epilepsia_pm %></td>
        <td><%= historial_paciente.alcohol %></td>
        <td><%= historial_paciente.deportes %></td>
        <td><%= historial_paciente.tabaco %></td>
        <td><%= historial_paciente.drogas %></td>
        <td><%= historial_paciente.estatus %></td>
        <td><%= link_to 'Ver', historial_paciente %></td>
        <td><%= link_to 'Modificar', edit_historial_paciente_path(historial_paciente) %></td>
        <td><%= link_to 'Eliminar', historial_paciente, method: :delete, data: { confirm: '¿Está seguro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%#= link_to 'Registrar nuevo Historial de Paciente', new_historial_paciente_path %>
</div>
</div>
</div>

app/views/historial_pacientes/new.html.erb
<div class="row center-xs">
  <div class="col-xs-8 col-md-6">
  <div class="box">

<h1>Nuevo Historial de Paciente</h1>

<%= render 'form', historial_paciente: @historial_paciente %>

<%= link_to 'Regresar', historial_pacientes_path %>
</div>
</div>
</div>

app/views/historial_pacientes/show.html.erb
<div class="row center-xs">
  <div class="col-xs-8 col-md-6">
  <div class="box">

<p id="notice"><%= notice %></p>

<p>
  <strong>Id:</strong>
  <%= @historial_paciente.id %>
</p>

<p>
  <strong>Prob cardio:</strong>
  <%= @historial_paciente.prob_cardio %>
</p>

<p>
  <strong>Prob respira:</strong>
  <%= @historial_paciente.prob_respira %>
</p>

<p>
  <strong>Diabetes:</strong>
  <%= @historial_paciente.diabetes %>
</p>

<p>
  <strong>Alergias:</strong>
  <%= @historial_paciente.alergias %>
</p>

<p>
  <strong>Diab pm:</strong>
  <%= @historial_paciente.diab_pm %>
</p>

<p>
  <strong>Sobrepso pm:</strong>
  <%= @historial_paciente.sobrepso_pm %>
</p>

<p>
  <strong>Hipertension pm:</strong>
  <%= @historial_paciente.hipertension_pm %>
</p>

<p>
  <strong>Epilepsia pm:</strong>
  <%= @historial_paciente.epilepsia_pm %>
</p>

<p>
  <strong>Alcohol:</strong>
  <%= @historial_paciente.alcohol %>
</p>

<p>
  <strong>Deportes:</strong>
  <%= @historial_paciente.deportes %>
</p>

<p>
  <strong>Tabaco:</strong>
  <%= @historial_paciente.tabaco %>
</p>

<p>
  <strong>Drogas:</strong>
  <%= @historial_paciente.drogas %>
</p>

<p>
  <strong>Estatus:</strong>
  <%= @historial_paciente.estatus %>
</p>

<%= link_to 'Editar', edit_historial_paciente_path(@historial_paciente) %> |
<%= link_to 'Regresar', historial_pacientes_path %>
</div>
</div>
</div>