config/routes.rb
Rails.application.routes.draw do
  resources :servicios
  resources :historial_pacientes
  resources :plan_quirurgicos
  resources :medicos
  resources :clinicas
  resources :especialidads
  resources :pacientes
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }
  root 'bienvenido#index'  
  resources :rols
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
      user ||= User.new # guest user (not logged in)
       if user.rol_id==2
       can :paciente, :all
       else
        can :read, :all
       end
    
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/clinica.rb
class Clinica < ApplicationRecord
  belongs_to :user, dependent: :destroy
  accepts_nested_attributes_for :user
  has_many :medicoen_clinicas
  has_many :medicos, through: :medicoen_clinicas
end

app/models/especialidad.rb
class Especialidad < ApplicationRecord
	self.table_name = "especialidads"
	has_many :medicos
end

app/models/historial_paciente.rb
class HistorialPaciente < ApplicationRecord
  belongs_to :paciente
end

app/models/medico.rb
class Medico < ApplicationRecord
  belongs_to :especialidad
  belongs_to :user, dependent: :destroy
  accepts_nested_attributes_for :user
  has_many :medicoen_clinicas
  has_many :clinicas, through: :medicoen_clinicas
  after_create :save_clinicas
  def clinicas=(value)
  	@clinicas = value
  end

  private
  def save_clinicas
  	@clinicas.each do |clinica_id|
  		MedicoenClinica.create(clinica_id: clinica_id, medico_id: self.id)
  	
  end
end
end

app/models/medicoen_clinica.rb
class MedicoenClinica < ApplicationRecord
  belongs_to :clinica
  belongs_to :medico
end

app/models/paciente.rb
class Paciente < ApplicationRecord
  belongs_to :user, dependent: :destroy
  accepts_nested_attributes_for :user
end

app/models/plan_quirurgico.rb
class PlanQuirurgico < ApplicationRecord
  belongs_to :medico
  belongs_to :paciente
  mount_uploader :examen, ExamenUploader
  has_many :servicio_seleccionados
  has_many :plan_quirurgicos, through: :servicio_seleccionados
  after_create :save_servicios
	  def servicios=(value)
	  	@servicios = value
	  end

	  private
	  	def save_servicios
	  		@servicios.each do |servicio_id|
	  			ServicioSeleccionado.create(servicio_id: servicio_id, plan_quirurgico_id: self.id)
	  	
	  	end
	  end
end

app/models/rol.rb
class Rol < ApplicationRecord
	self.table_name = "rols"
	has_many :users
end

app/models/servicio.rb
class Servicio < ApplicationRecord
  has_many :servicio_seleccionados
  has_many :plan_quirurgicos, through: :servicio_seleccionados
end

app/models/servicio_seleccionado.rb
class ServicioSeleccionado < ApplicationRecord
  belongs_to :servicio
  belongs_to :plan_quirurgico
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  belongs_to :rol
  has_one :paciente
  has_one :medico
  has_one :clinica

end

app/controllers/medicos_controller.rb
class MedicosController < ApplicationController
  before_action :set_medico, only: [:show, :edit, :update, :destroy]

  # GET /medicos
  # GET /medicos.json
  def index
    @medicos = Medico.where(:estatus => "A")
  end

  # GET /medicos/1
  # GET /medicos/1.json
  def show
  end

  # GET /medicos/new
  def new
    @medico = Medico.new
    @medico.user = User.new
    @especialidades = Especialidad.where(:estatus => "A")
    @clinicas = Clinica.where(:estatus => "A")
  end

  # GET /medicos/1/edit
  def edit
  end

  # POST /medicos
  # POST /medicos.json
  def create
    @medico = Medico.new(medico_params)
    @medico.clinicas = params[:clinicas]
    @medico.estatus = "A" 
    respond_to do |format|
      if @medico.save
        format.html { redirect_to @medico, notice: 'El médico fue registrado exitosamente.' }
        format.json { render :show, status: :created, location: @medico }
      else
        format.html { render :new }
        format.json { render json: @medico.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /medicos/1
  # PATCH/PUT /medicos/1.json
  def update
    respond_to do |format|
      if @medico.update(medico_params)
        format.html { redirect_to @medico, notice: 'Los datos del médico han sido modificado exitosamente.' }
        format.json { render :show, status: :ok, location: @medico }
      else
        format.html { render :edit }
        format.json { render json: @medico.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /medicos/1
  # DELETE /medicos/1.json
  def destroy
    @medico = Medico.find(params[:id])
    @medico.estatus = "I"      
    @medico.save
    respond_to do |format|
      format.html { redirect_to medicos_url, notice: 'El médico ha sido eliminado exitosamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_medico
      @medico = Medico.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def medico_params
      params.require(:medico).permit(:user_id, :especialidad_id, :nombres, :apellidos, :direccion, :telefono, :edad, :sexo, :estatus, :clinicas, user_attributes: [:email, :password, :password_confirmation, :rol_id])
    end
end

app/controllers/rols_controller.rb
class RolsController < ApplicationController
	before_action :set_rol, only: [:show, :edit, :update, :destroy]  
  # GET /rols
  # GET /rols.json
  def index
    @rols = Rol.where(:estatus => "A")
  end

  # GET /rols/1
  # GET /rols/1.json
  def show
  end

  # GET /rols/new
  def new
    @rol = Rol.new
  end

  # GET /rols/1/edit
  def edit
  end

  # POST /rols
  # POST /rols.json
  def create
    @rol = Rol.new(rol_params)
    @rol.estatus = "A" 
    respond_to do |format|
      if @rol.save
        format.html { redirect_to @rol, notice: 'El Rol ha sido creado exitosamente.' }
        format.json { render :show, status: :created, location: @rol }
      else
        format.html { render :new }
        format.json { render json: @rol.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rols/1
  # PATCH/PUT /rols/1.json
  def update
    respond_to do |format|
      if @rol.update(rol_params)
        format.html { redirect_to @rol, notice: 'El Rol ha sido modificado exitosamente.' }
        format.json { render :show, status: :ok, location: @rol }
      else
        format.html { render :edit }
        format.json { render json: @rol.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rols/1
  # DELETE /rols/1.json
  def destroy
    @rol = Rol.find(params[:id])
    @rol.estatus = 'I'      
    @rol.save
    respond_to do |format|
      format.html { redirect_to rols_url, notice: 'El rol ha sido eliminado exitosamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rol
      @rol = Rol.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rol_params
      params.require(:rol).permit(:descripcion, :estatus)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bienvenido_helper.rb
module BienvenidoHelper
end

app/helpers/clinicas_helper.rb
module ClinicasHelper
end

app/helpers/especialidads_helper.rb
module EspecialidadsHelper
end

app/helpers/medicos_helper.rb
module MedicosHelper
end

app/helpers/pacientes_helper.rb
module PacientesHelper
end

app/helpers/rols_helper.rb
module RolsHelper
end

app/helpers/servicios_helper.rb
module ServiciosHelper
end

app/views/medicos/_form.html.erb
<div class="row center-xs">
  <div class="col-xs-8 col-md-6">
  <div class="box">

<%= form_with(model: medico, local: true) do |form| %>
  <% if medico.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(medico.errors.count, "error") %> prohibited this medico from being saved:</h2>

      <ul>
      <% medico.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  
  <div class="field">
    <%= form.label :especialidad_id %>
    
    <%=collection_select(:medico, :especialidad_id, @especialidades, :id, :descripcion, prompt: true)%>
  </div>

  <div class="field">
    <%= form.label :nombres %>
    <%= form.text_field :nombres, id: :medico_nombres, class:"form-control" %>
  </div>

  <div class="field">
    <%= form.label :apellidos %>
    <%= form.text_field :apellidos, id: :medico_apellidos, class:"form-control" %>
  </div>

  <div class="field">
    <%= form.label :direccion %>
    <%= form.text_field :direccion, id: :medico_direccion, class:"form-control" %>
  </div>

  <div class="field">
    <%= form.label :telefono %>
    <%= form.text_field :telefono, id: :medico_telefono, class:"form-control" %>
  </div>

  <div class="field">
    <%= form.label :edad %>
    <%= form.text_field :edad, id: :medico_edad, class:"form-control" %>
  </div>

  <div class="field">
    <%= form.label :sexo %>
    <%= form.text_field :sexo, id: :medico_sexo, class:"form-control" %>
  </div>
  <div class="field">
    <label> Clinicas</label>
    <% @clinicas.each do |clinica| %>
      <div class="field">
        <%= check_box_tag "clinicas[]", clinica.id %> <%= clinica.nombre%>
      </div>
    <% end%>
  </div>



  <%= form.fields_for :user do |f| %>
    <div class="field">
            <%= f.label :email %><br />
            <%= f.email_field :email, autofocus: true, autocomplete: "email", class:"form-control" %>
          </div>

          <div class="field">
            <%= f.label :contraseña %>
            <% if @minimum_password_length %>
            <em>(<%= @minimum_password_length %> caracteres como mínimo)</em>
            <% end %><br />
            <%= f.password_field :password, autocomplete: "off", class:"form-control" %>

          </div>

          <div class="field">
            <%= f.label :confirmar_contraseña %><br />
            <%= f.password_field :password_confirmation, autocomplete: "off", class:"form-control" %>
          </div>
          
          <% #if not user_signed_in?%>
            <%= f.hidden_field :rol_id, :value => 3 %>
          <%#end%>

            <%= f.hidden_field :estatus, :value => "A" %>
  <%end%>
  <div class="actions">
   <%= form.submit "Guardar", class:"btn btn-primary b" %>
  </div>
<% end %>
</div>
</div>
</div>

app/views/medicos/edit.html.erb
<div class="row center-xs">
  <div class="col-xs-8 col-md-6">
  <div class="box">

<h1>Editar Medico</h1>

<%= render 'form', medico: @medico %>

<%= link_to 'Ver', @medico %> |
<%= link_to 'Regresar', medicos_path %>
</div>
</div>
</div>

app/views/medicos/index.html.erb
<div class="row ">
  <div class="col-xs-8 col-md-6">
  <div class="box">

<p id="notice"><%= notice %></p>

<h1 class="right" >Lista de Médicos</h1>

<table width="203%" border="1" cellpadding="0" cellspacing="0" bordercolor="#2f4f4f">
  <thead>
    <tr>
      <th height="10%" width="10%">Especialidad</th>
      <th height="10%" width="10%">Nombres</th>
      <th height="10%" width="10%">Apellidos</th>
      <th height="10%" width="10%">Direccion</th>
      <th height="10%" width="10%">Telefono</th>
      <th height="10%" width="10%">Edad</th>
      <th height="10%" width="10%">Sexo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @medicos.each do |medico| %>
      <tr>>
        <td height="10%" width="10%"><%= medico.especialidad_id %></td>
        <td height="10%" width="10%"><%= medico.nombres %></td>
        <td height="10%" width="10%"><%= medico.apellidos %></td>
        <td height="10%" width="10%"><%= medico.direccion %></td>
        <td height="10%" width="10%"><%= medico.telefono %></td>
        <td height="10%" width="10%"><%= medico.edad %></td>
        <td height="10%" width="10%"><%= medico.sexo %></td>
        <td><%= link_to 'Ver', medico %></td>
        <td><%= link_to 'Modificar', edit_medico_path(medico) %></td>
        <td><%= link_to 'Eliminar', medico, method: :delete, data: { confirm: 'Esta Seguro que quiere eliminar al médico?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Registrar Médico', new_medico_path %>
</div>
</div>
</div>

app/views/medicos/new.html.erb
<div class="row center-xs">
  <div class="col-xs-8 col-md-6">
  <div class="box">

<h1>Nuevo Médico</h1>

<%= render 'form', medico: @medico %>

<%#= link_to 'Regresar', medicos_path %>
</div>
</div>
</div>

app/views/medicos/show.html.erb
<div class="row center-xs">
  <div class="col-xs-8 col-md-6">
  <div class="box">

<p id="notice"><%= notice %></p>

<!--><p>
  
  <%#= @medico.id%>
</p>
</-->
<p>
  <strong>Especialidad:</strong>
  <%#= @medico.especialidad %>
</p>

<p>
  <strong>Nombres:</strong>
  <%= @medico.nombres %>
</p>

<p>
  <strong>Apellidos:</strong>
  <%= @medico.apellidos %>
</p>

<p>
  <strong>Direccion:</strong>
  <%= @medico.direccion %>
</p>

<p>
  <strong>Telefono:</strong>
  <%= @medico.telefono %>
</p>

<p>
  <strong>Edad:</strong>
  <%= @medico.edad %>
</p>

<p>
  <strong>Sexo:</strong>
  <%= @medico.sexo %>
</p>

<%= link_to 'Editar', edit_medico_path(@medico) %> |
<%= link_to 'Regresar', medicos_path %>
</div>
</div>
</div>

app/views/rols/_form.html.erb
<%= form_with(model: rol, local: true) do |form| %>
  <% if rol.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(rol.errors.count, "error") %> prohibited this rol from being saved:</h2>

      <ul>
      <% rol.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :descripcion %>
    <%= form.text_field :descripcion, id: :rol_descripcion %>
  </div>

  
  <div class="actions">
    <%= form.submit "Guardar", class:"btn btn-primary b" %>
  </div>
<% end %>

app/views/rols/edit.html.erb
<h1>Editing Rol</h1>

<%= render 'form', rol: @rol %>

<%= link_to 'Show', @rol %> |
<%= link_to 'Back', rols_path %>

app/views/rols/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Rols</h1>

<table>
  <thead>
    <tr>
      <th>Descripcion</th>
      <th>Estatus</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rols.each do |rol| %>
      <tr>
        <td><%= rol.descripcion %></td>
        <td><%= rol.estatus %></td>
        <td><%= link_to 'Ver', rol %></td>
        <td><%= link_to 'Modificar', edit_rol_path(rol) %></td>
        <td><%= link_to 'Eliminar', rol, method: :delete, data: { confirm: '¿Seguro que quiere eliminar al Rol?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Registrar nuevo rol', new_rol_path %>

app/views/rols/new.html.erb
<h1>New Rol</h1>

<%= render 'form', rol: @rol %>

<%= link_to 'Back', rols_path %>

app/views/rols/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Descripcion:</strong>
  <%= @rol.descripcion %>
</p>

<p>
  <strong>Estatus:</strong>
  <%= @rol.estatus %>
</p>

<%= link_to 'Edit', edit_rol_path(@rol) %> |
<%= link_to 'Back', rols_path %>